name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: todo_user
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: todo_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U todo_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # -------------------------
      # Backend
      # -------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install backend dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Run Alembic migrations
        run: |
          cd backend
          alembic upgrade head
        env:
          DATABASE_URL: postgresql://todo_user:secret@postgres:5432/todo_db
          POSTGRES_USER: todo_user
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: todo_db

      - name: Run backend tests
        working-directory: backend
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest
        env:
          DATABASE_URL: postgresql://todo_user:secret@postgres:5432/todo_db

      # -------------------------
      # Frontend
      # -------------------------
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install frontend deps & build
        working-directory: frontend
        run: |
          npm install
          npm run build

      # -------------------------
      # Docker build check
      # -------------------------
      - name: Build backend Docker image
        run: docker build ./backend -t todo-backend:latest

      - name: Build frontend Docker image
        run: docker build ./frontend -t todo-frontend:latest
